# Konfiguracja Doctrine Migrations
doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    all_or_nothing: true
    transactional: true
    check_database_platform: true
    organize_migrations: false
    connection: null
    em: null
